[package]
name = "cyanea-py"
description = "Python bindings (PyO3) for the Cyanea bioinformatics ecosystem"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "cyanea"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
cyanea-core  = { path = "../cyanea-core",  features = ["std"] }
cyanea-seq   = { path = "../cyanea-seq",   features = ["std"] }
cyanea-io    = { path = "../cyanea-io",    default-features = false }
cyanea-align = { path = "../cyanea-align", features = ["std"] }
cyanea-stats = { path = "../cyanea-stats", features = ["std"] }
cyanea-ml    = { path = "../cyanea-ml",    features = ["std"] }
